# Generated by Django 5.2 on 2025-05-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservadeservicio',
            old_name='emeplado',
            new_name='empleado',
        ),
        migrations.CreateModel(
            name='ServiciosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_servicio', models.DateTimeField()),
                ('total_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_eventos.cliente')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_eventos.coordinador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_eventos.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_eventos.servicio')),
            ],
        ),
    ]
